/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller.constants;

/**
 *
 * @author Zakhar
 */
public class ConstantsController {
    public final static String PASSWORD_SALT = "GtXcvpo$%#97&";
    public static final String GET_MONTH_NUMBER_REG = "^\\d+";
    public static final String GET_PRICE_REG = "\\d+[.]{1,1}\\d*";
    
    public static final String LANGUAGE_EN = "en";
    public static final String COUNTRY_US = "US";
    public static final String LANGUAGE_UK = "uk";
    public static final String COUNTRY_UA = "UA";
    public static final String LANGUAGE_INPUT_UK = "UKR";
    
    public static final String ISO_ENCOD = "ISO-8859-1";
    public static final String UTF8_ENCOD = "UTF8";
    
    public static final String EMPTY_STR = "";
    
    public static final String LOGIN_FIELD = "loginField";
    public static final String LOGIN = "login";
    public static final String PERIODICALS = "periodicals";
    public static final String ARTICLES_NOT_PERMITTED = "articlesNotPermitted";
    public static final String OBJECT_LIST = "objectList";
    public static final String LOCALE_SESSION_KEY = "locale";
    public static final String BUNDLE_DIR = "bundles/Bundle";
    public static final String ERROR_PAGE = "/error.jsp";
    public static final String LANGUAGE_STR = "language";
    public static final String JPG_FORMAT = ".jpg";
    
    public static final String SUPERADMIN_JSP = "superadmin.jsp";
    public static final String SUPERADMIN_LOGIN_JSP = "superadmin_login.jsp";
    public static final String SUPERADMINUSER_JSP = "superadminuser.jsp";
    public static final String MAIN_JSP = "main.jsp";
    public static final String PERIODICAL_JSP = "periodical.jsp";
    public static final String PERIODICALUNSIGNED_JSP = "periodicalunsigned.jsp";
    public static final String REGISTER_JSP = "register.jsp";
    public static final String REPLENISH_JSP = "replenish.jsp";
    public static final String USER_JSP = "user.jsp";
    public static final String WRITEARTICLE_JSP = "writearticle.jsp";
    
    public static final String LOGIMG = "logimg";
    public static final String PASSWORD_REP = "passwordRep";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String FATHER_NAME = "fatherName";
    
    
    public static final String CREATE_NEW_PUBLICATION_MESSAGE = "createNewPublicationMessage";
    public static final String DELETE_PERIODICAL_ARTICLE_MESSAGE = "deletePeriodicalArticleMessage";
    public static final String PERMIT_ARTICLE_MESSAGE = "permitArticleMessage";
    public static final String TITLE_MESSAGE = "titleMessage";
    public static final String PRICE_MESSAGE = "priceMessage";
    public static final String LOGOUT_SUBMIT = "logoutSubmit";
    public static final String USER_MANAGEMENT_SUBMIT = "userManagementSubmit";
    public static final String CREATE_SUBMIT = "createSubmit";
    public static final String DELETE_SUBMIT = "deleteSubmit";
    public static final String DELETE_ARTICLE_SUBMIT = "deleteArticleSubmit";
    public static final String VIEW_SUBMIT = "viewSubmit";
    public static final String PERMIT_SUBMIT = "permitSubmit";
    public static final String UNBLOCKED_USER = "unblockedUsers";
    public static final String PERIODICAL_ARTICLES = "periodicalArticles";
    public static final String ARTICLES = "articles";
    public static final String SUBJECT = "subject";
    public static final String ARTICLES_NOT_PERMITED = "articlesNotPermitted";
    public static final String ARTICLES_NOT_PERMITED_NAME = "articlesNotPermittedName";
    public static final String USER_EMAIL = "usersEmail";
    public static final String LOGIN_AS_SUPERADMIN_MESSAGE = "loginAsSuperadminMessage";
    public static final String LOGIN_MESSAGE = "loginMessage";
    public static final String PASSWORD_MESSAGE = "passwordMessage";
    public static final String LOGIN_SUBMIT = "logInSubmit";
    public static final String PASSWORD = "password";
    public static final String IS_LOGINED = "isLogined";
    public static final String FIELD_FAIL_INFO = "fieldFailInfo";
    public static final String ADMINS = "admins";
    public static final String USERS_SIMPLE = "usersSimple";
    public static final String TITLE_PERIODICAL = "titlePeriodical";
    public static final String PRICE_PERIODICAL = "pricePeriodical";
    public static final String BLOCK_USER = "blockUser";
    public static final String UNBLOCK_USER = "unblockUser";
    public static final String USER_ALL = "usersAll";
    public static final String USERS_UNBLOCKED = "usersUnblocked";
    public static final String USERS_BLOCKED = "usersBlocked";
    public static final String PERIODICALS_MANAGEMENT_SUBMIT = "periodicalsManagementSubmit";
    public static final String SET_ADMIN_RIGHTS_MESSAGE = "setAdminRightsMessage";
    public static final String SET_ADMIN_SUBMIT = "setAdminSubmit";
    public static final String UNSET_ADMIN_SUBMIT = "unsetAdminSubmit";
    public static final String DELETE_USER_MESSAGE = "deleteUserMessage";
    public static final String UNBLOCK_SUBMIT = "unblockSubmit";
    public static final String BLOCK_SUBMIT = "blockSubmit";
    public static final String PAY_MESSAGE = "payMessage";
    public static final String PAY_SUBMIT = "paySubmit";
    public static final String BLOCK_MESSAGE = "blockMessage";
    public static final String ARTICLE_AUTHOR_NAME_FIELD = "articleAuthorNameField";
    public static final String ARTICLES_NOT_PERMITTED_NAME = "articlesNotPermittedName";
    public static final String ARTICLE_DATE_FIELD = "articleDateField";
    public static final String ARTICLE_NAME_FIELD = "articleNameField";
    public static final String ARTICLE_REVIEW_FIELD = "articleReviewField";
    public static final String ARTICLE_NAME = "articleName";
    public static final String ARTICLE_TEXT_FIELD = "articleTextField";
    public static final String PERMIT_UNCHECKED = "permitUnchecked";
    public static final String DELETE_UNCHECKED = "deleteUnchecked";
    public static final String BLOCKED_USERS = "blockedUsers";
    
    public static final String REGISTER_USER = "registerUser";
    public static final String START_PAGE = "startPage";
    public static final String REGISTER_DO = "registerDo";
    public static final String LOGIN_USER = "loginUser";
    public static final String LOGOUT = "logout";
    public static final String MORE_ABOUT_PERIODICAL = "moreAboutPeriodical";
    public static final String GET_ACQUAINTED = "getAcquainted";
    public static final String OPEN_PERIODICAL = "openPeriodical";
    public static final String OPEN_ARTICLE = "openArticle";
    public static final String BACK_TO_USER = "backToUser";
    public static final String BACK_TO_PERIODICALS = "backToPeriodicals";
    public static final String REPLENISH_ACCOUNT = "replenishAccount";
    public static final String REPLENISH = "replenish";
    public static final String SIGNE_UP = "signeUp";
    public static final String USER = "user";
    public static final String CHOOSE_PERIODICAL_TO_WRITE_ARTICLE = "choosePeriodicalToWriteArticle";
    public static final String SEND_ARTICLE = "sendArticle";
    public static final String VIEW_UNCHECKED_ARTICLE = "viewUncheckedArticle";
    public static final String PERMIT_ARTICLE_USER = "permitArticleUser";
    public static final String DELETE_UNPERMITED_ARTICLE_USER = "deleteUnpermitedArticleUser";
    public static final String LOGIN_ADMIN = "loginAdmin";
    public static final String LOGOUT_ADMIN = "logoutAdmin";
    public static final String CREATE_PERIODICAL = "createPeriodical";
    public static final String SUPERADMIN = "superadmin";
    public static final String LANGUAGE = "language";
    public static final String DELETE_PERIODICAL = "deletePeriodical";
    public static final String UNSET_ADMIN = "unsetAdmin";
    public static final String DELETE_USER = "deleteUser";
    public static final String SET_ADMIN = "setAdmin";
    public static final String DELETE_PERIODICAL_ARTICLE = "deletePeriodicalArticle";
    public static final String DELETE_ARTICLE = "deleteArticle";
    public static final String PERMIT_ARTICLE = "permitArticle";
    public static final String DELETE_UNPERMITED_ARTICLE = "deleteUnpermitedArticle";
    public static final String VIEW_ARTICLE = "viewArticle";
    public static final String PAY_FOR_ARTICLES = "payForArticles";
    public static final String USER_MANAGEMENT = "userManagement";
    public static final String PERIODICALS_MANAGEMENT = "periodicalsManagement";
    public static final String OPEN_ARTICLE_USER = "openArticle";
    public static final String ARTICLE_NAME_USER = "articleName";
    public static final String SUBJECT_OPEN_USER = "subjectOpen";
    public static final String ARTICLES_USER = "articles";
    public static final String AUTH_NUM = "authNum";
    public static final String EMAIL_PAGE_INFO = "emailPageInfo";
    public static final String PASSWORD_PAGE_INFO = "passwordPageInfo";
    public static final String LOG_IN_SUBMIT = "loginSubmit";
    public static final String REGISTRATION_SUBMIT = "registrationSubmit";
    public static final String AVAILABLE_PERIODICALS_PAGE_INFO = "availablePeriodicalsPageInfo";
    public static final String AUTHORS_NUMBER_PAGE_INFO = "authorsNumberPageInfo";
    public static final String LANGUAGE_USER = "languageUser";
    public static final String LANGUAGE_REGISTER = "languageRegister";
    public static final String LANGUAGE_PERIODICAL_UNSIGNED = "languagePeriodicalunsigned";
    public static final String LANGUAGE_PERIODICAL = "languagePeriodical";
    public static final String LANGUAGE_MAIN = "languageMain";
    public static final String LANGUAGE_REPLENISH = "languageReplenish";
    public static final String LANGUAGE_WRITE_ARTICLE = "languageWriteArticle";
    public static final String LANGUAGE_ADMIN = "languageAdmin";
    public static final String LANGUAGE_ADMIN_USER_MANAGEMENT = "languageAdminUserManagement";
    public static final String LANGUAGE_ADMIN_LOGIN = "languageAdminlogin";
    public static final String EMAIL = "email";
    public static final String IS_WRITER = "isWriter";
    public static final String IS_ADMIN = "isAdmin";
    public static final String USERNAME ="username";
    public static final String NAME_FIELD = "nameField";
    public static final String ACCOUNT = "account";
    public static final String IS_AUTHOR_FIELD = "isAuthorField";
    public static final String IS_ADMIN_FIELD = "isAdminField";
    public static final String SUBJECT_OPEN = "subjectOpen";
    public static final String SUBSCRIPTION_DATE = "subscriptionDate";
    public static final String REPLENISH_ACCOUNT_SUBMIT = "replenishAccountSubmit";
    public static final String BACK_SUBMIT = "backSubmit";
    public static final String DATE_SUBSCRIPTION_PAGE_INFO = "dateSubscriptionPageInfo";
    public static final String AVAILABLE_ARTICLES_PAGE_INFO = "availableArticlesPageInfo";
    public static final String OPEN_SUBMIT = "openSubmit";
    public static final String CURRENT_ARTICLE_TITLE = "currentArticleTitle";
    public static final String REVIEW = "review";
    public static final String ARTICLES_NUM = "articlesNum";
    public static final String MONTHES_COST = "monthesCost";
    public static final String SIGNE_UP_PAGE_INFO = "signeUpPageInfo";
    public static final String ADDON_SIGNE_PAGE_INFO = "addonSignePageInfo";
    public static final String SIGNE_UP_SUBMIT = "signeUpSubmit";
    public static final String ADDON_INFO = "addonInfo";
    public static final String SUBJECT_PAGE_INFO = "subjectPageInfo";
    public static final String PRICE_PAGE_INFO = "pricePageInfo";
    public static final String ARTICLES_NUMBER_PAGE_INFO = "articlesNumberPageInfo";
    public static final String FOLLOWERS_NUMBER_PAGE_INFO = "followersNumberPageInfo";
    public static final String FIRST_NAME_PAGE_INFO = "firstNamePageInfo";
    public static final String MIDDLE_NAME_PAGE_INFO = "middleNamePageInfo";
    public static final String LAST_NAME_PAGE_INFO = "lastNamePageInfo";
    public static final String GET_ACQUINTED_SUBMIT = "getAcquintedSubmit";
    public static final String FIELD_SUC_INFO = "fieldSucInfo";
    public static final String REPEAT_PASSWORD_PAGE_INFO = "repeatPasswordPageInfo";
    public static final String ENTER_FROM_PIC_PAGE_INFO = "enterFromPicPageInfo";
    public static final String REQUIRED_FIELDS_PAGE_INFO = "requiredFieldsPageInfo";
    public static final String REGISTER_SUBMIT = "registerSubmit";
    public static final String MAIN_SUBMIT = "mainSubmit";
    public static final String REPLENISH_PAGE_INFO = "replenishPageInfo";
    public static final String REPLENISH_SUBMIT = "replenishSubmit";
    public static final String MONEY = "money";
    public static final String MONTH_COST = "monthCost";
    public static final String CLOSE_UNCHECKED = "closeUnchecked";
    public static final String PERIODICALS_PAYED = "periodicalsPayed";
    public static final String PERIODICALS_PAGE_INFO = "periodicalsPageInfo";
    public static final String AVAILABLE_PAGE_INFO = "availablePageInfo";
    public static final String SIGNED_PAGE_INFO = "signedPageInfo";
    public static final String WRITE_ARTICLES_PAGE_INFO = "writeArticlePageInfo";
    public static final String ADDON_INFO_SUBMIT = "addonInfoSubmit";
    public static final String CHOOSE_SUBMIT = "chooseSubmit";
    public static final String SUBJECT_TO_WRITE = "subjectToWrite";
    public static final String ANNOTATION = "annotation";
    public static final String ARTICLE_TEXT = "articleText";
    public static final String SEND_SUBMIT = "sendSubmit";
    public static final String ANNOTATION_PAGE_INFO = "annotationPageInfo";
    public static final String TEXT_PAGE_INFO = "textPageInfo";
    public static final String TITLE_PAGE_INFO = "titlePageInfo";
    
    public static final String LOCALE_KEY_CREATE_PERIODICAL = "key.page.info.new_publication";
    public static final String LOCALE_KEY_DELETE_PERIODICAL_ARTICLE = "key.page.info.delete_periodical_article";
    public static final String LOCALE_KEY_PERMIT_ARTICLE = "key.page.info.permit_article";
    public static final String LOCALE_KEY_TITLE = "key.page.info.title";
    public static final String LOCALE_KEY_PRICE = "key.page.info.monthprice";
    public static final String LOCALE_KEY_LOGOUT_SUBMIT = "key.submit.logout";
    public static final String LOCALE_KEY_LOGOIN_SUBMIT = "key.submit.login";
    public static final String LOCALE_KEY_USER_MANAGEMENT_BUTTON = "key.submit.user_management";
    public static final String LOCALE_KEY_CREATE_SUBMIT = "key.submit.create";
    public static final String LOCALE_KEY_DELETE_SUBMIT = "key.submit.delete";
    public static final String LOCALE_KEY_DELETE_ARTICLE_SUBMIT = "key.submit.delete_article";
    public static final String LOCALE_KEY_VIEW_SUBMIT = "key.submit.view";
    public static final String LOCALE_KEY_PERMIT_SUBMIT = "key.submit.permit";
    public static final String LOCALE_KEY_PERIODICALS_MANAGEMENT = "key.submit.periodicals_management";
    public static final String LOCALE_KEY_PERIODICALS_SET_ADMIN_RIGHTS = "key.page.info.set_admin_rights";
    public static final String LOCALE_KEY_UNSET_ADMIN_SUBMIT = "key.submit.unset_admin";
    public static final String LOCALE_KEY_SET_ADMIN_SUBMIT = "key.submit.set_admin";
    public static final String LOCALE_KEY_DELETE_USER = "key.page.info.delete_user";
    public static final String LOCALE_KEY_UNBLOCK_SUBMIT = "key.submit.unblock";
    public static final String LOCALE_KEY_BLOCK_SUBMIT = "key.submit.block";
    public static final String LOCALE_KEY_PAY_MESSAGE = "key.page.info.pay_for_articles";
    public static final String LOCALE_KEY_PAY_SUBMIT = "key.submit.pay";
    public static final String LOCALE_KEY_BLOCK_USER = "key.page.info.block_user";
    public static final String LOCALE_KEY_LOGIN_AS_SUPERADMIN = "key.page.info.loginAsSuperadmin";
    public static final String LOCALE_KEY_LOGIN_MESSAGE = "key.page.info.login";
    public static final String LOCALE_KEY_PASSWORD_MESSAGE = "key.page.info.password";
    public static final String LOCALE_KEY_EMAIL_LOGIN_MESSAGE = "key.page.info.email_login";
    public static final String LOCALE_KEY_REGISTRATION_SUBMIT = "key.submit.registration";
    public static final String LOCALE_KEY_AVAILABLE_PERIODICALS = "key.page.info.available_periodicals";
    public static final String LOCALE_KEY_AUTHORS_NUMBER = "key.page.info.authors_number";
    public static final String LOCALE_KEY_LOGIN_NOT_CORRECT = "key.message.not_correct_login_password";
    public static final String LOCALE_KEY_VALUES_NOT_CORRECT = "key.message.not_correct_values";
    public static final String LOCALE_KEY_FIRST_NAME = "key.page.info.first_name";
    public static final String LOCALE_KEY_MIDDLE_NAME = "key.page.info.middle_name";
    public static final String LOCALE_KEY_LAST_NAME = "key.page.info.last_name";
    public static final String LOCALE_KEY_EMAIL_REG = "key.page.info.email";
    public static final String LOCALE_KEY_PASSWORD_REG = "key.page.info.password_reg";
    public static final String LOCALE_KEY_REPEAT_PASS_REG = "key.page.info.repeat_password";
    public static final String LOCALE_KEY_ENTER_FROM_PIC = "key.page.info.enter_img_symbols";
    public static final String LOCALE_KEY_REQUIRED_FIELDS = "key.page.info.required_fields";
    public static final String LOCALE_KEY_REGISTER_SUBMIT = "key.submit.register";
    public static final String LOCALE_KEY_MAIN_SUBMIT = "key.submit.main";
    public static final String LOCALE_KEY_REPLENISH_ACCOUNT_SUBMIT = "key.submit.replenish_account";
    public static final String LOCALE_KEY_PERIODICALS = "key.page.info.periodicals";
    public static final String LOCALE_KEY_AUTHOR = "key.page.message.author";
    public static final String LOCALE_KEY_ADMIN = "key.page.message.admin";
    public static final String LOCALE_KEY_AVAILABLE = "key.page.info.available";
    public static final String LOCALE_KEY_SIGNED = "key.page.info.signed";
    public static final String LOCALE_KEY_WRITE_ARTICLE = "key.page.info.write_new_article";
    public static final String LOCALE_KEY_OPEN_SUBMIT = "key.submit.open";
    public static final String LOCALE_KEY_CHOOSE_SUBMIT = "key.submit.choose";
    public static final String LOCALE_KEY_ADDON_INFO_SUBMIT = "key.submit.additional_info";
    public static final String LOCALE_KEY_CLOSE_SUBMIT = "key.submit.close";
    public static final String LOCALE_KEY_SIGNE_UP = "key.page.info.signe_up";
    public static final String LOCALE_KEY_ADDON_SIGNE_UP_INFO = "key.page.info.addon_signe_up_info";
    public static final String LOCALE_KEY_SIGNE_UP_SUBMIT = "key.submit.signe_up";
    public static final String LOCALE_KEY_BACK_SUBMIT = "key.submit.back";
    public static final String LOCALE_KEY_ADDON_INFO = "key.page.info.addon_info";
    public static final String LOCALE_KEY_SUBJECT_INFO = "key.page.info.subject";
    public static final String LOCALE_KEY_PRICE_INFO = "key.page.info.monthprice";
    public static final String LOCALE_KEY_ARTICLES_NUMBER_INFO = "key.page.info.articles_number";
    public static final String LOCALE_KEY_FOLLOWERS_NUMBER_INFO = "key.page.info.followers_number";
    public static final String LOCALE_KEY_AVAILABLE_ARTICLES_INFO = "key.page.info.available_articles";
    public static final String LOCALE_KEY_GET_ACQUINTED_INFO = "key.submit.get_acquainted";
    public static final String LOCALE_KEY_SUBSCRIPTION_DATE_INFO = "key.page.info.subscription_continues";
    public static final String LOCALE_KEY_SEND_SUBMIT = "key.submit.send";
    public static final String LOCALE_KEY_ANNOTATION = "key.page.info.annotation";
    public static final String LOCALE_KEY_TEXT = "key.page.info.text";
    public static final String LOCALE_KEY_REPLENISH_ACCOUNT = "key.submit.replenish_account";
    public static final String LOCALE_KEY_REPLENISH_SUBMIT = "key.submit.replenish";
    public static final String LOCALE_KEY_SUBJECT = "key.page.info.subject";
    public static final String LOCALE_KEY_USER = "key.page.Info.user";
    public static final String LOCALE_KEY_REG_SUCK_MESSAGE = "key.page.info.reg_suck";
    public static final String EMAIL_IS_ALREADY_REGISTERED = "key.message.user_is_already_registered";
    
    public static final String NEW_ARTICLE_CREATED_MESSAGE = "new article has been created: ";
    
    private Map<String, Command> COMMAND_MAP = new HashMap<String, Command>()
    {{
        put(REGISTER_USER, new RegisterFormCommand());
        put(START_PAGE, new HomePageCommand());
        put(REGISTER_DO, new RegisterCommand());
        put(LOGIN_USER, new LoginCommand());
        put(LOGOUT, new LogoutCommand());
        put(MORE_ABOUT_PERIODICAL, new PeriodicalUnsignedCommand());
        put(GET_ACQUAINTED, new PeriodicalUnsignedCommand());
        put(OPEN_PERIODICAL, new PeriodicalPageCommand());
        put(OPEN_ARTICLE, new ArticlePageCommand());
        put(BACK_TO_USER, new UserPageCommand());
        put(BACK_TO_PERIODICALS, new PeriodicalPageCommand());
        put(REPLENISH_ACCOUNT, new ReplenishAccountPageCommand());
        put(REPLENISH, new ReplenishCommand());
        put(SIGNE_UP, new SignedUpPeriodicalCommand());
        put(USER, new HomePageCommand());
        put(CHOOSE_PERIODICAL_TO_WRITE_ARTICLE, new WriteArticlePageCommand());
        put(SEND_ARTICLE, new WriteArticleCommand());
        put(VIEW_UNCHECKED_ARTICLE, new UncheckedArticlePageCommand());
        put(PERMIT_ARTICLE_USER, new PermitArticleUserCommand());
        put(DELETE_UNPERMITED_ARTICLE_USER, new DeleteUnpermitedArticleUserCommand());
        put(LOGIN_ADMIN, new LoginSuperAdminCommand());
        put(LOGOUT_ADMIN, new LogoutSuperAdminCommand());
        put(CREATE_PERIODICAL, new SetPeriodicalCommand());
        put(SUPERADMIN, new LoginPageCommand());
        put(LANGUAGE, new LanguageCommand());
        put(DELETE_PERIODICAL, new DeletePeriodicalCommand());
        put(UNSET_ADMIN, new SetAdminFalseCommand());
        put(DELETE_USER, new DeleteUserCommand());
        put(SET_ADMIN, new SetAdminTrueCommand());        
        put(UNBLOCK_USER, new UnblockUserCommand());
        put(BLOCK_USER, new BlockUserCommand());
        put(DELETE_PERIODICAL_ARTICLE, new DeletePeriodicalArticlePageCommand());
        put(DELETE_ARTICLE, new DeleteArticleCommand());
        put(PERMIT_ARTICLE, new PermitArticleCommand());
        put(DELETE_UNPERMITED_ARTICLE, new DeleteUnpermitedArticleCommand());
        put(VIEW_ARTICLE, new ViewArticleCommand());
        put(PAY_FOR_ARTICLES, new PayForArticlesCommand());
        put(USER_MANAGEMENT, new UserManagementCommand());
        put(PERIODICALS_MANAGEMENT, new AdminPageCommand());
    }};
}
